FROM mcr.microsoft.com/dotnet/sdk:6.0 as build-env
WORKDIR /
COPY *.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as runtime
WORKDIR /publish
COPY --from=build-env /publish .
ENV ASPNETCORE_URLS=http://+:5013
EXPOSE 5013
ENTRYPOINT [ "dotnet", "HelloDocker2.dll" ]