name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: List files in the repository
        run: |
            ls 

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: rmanohar86
          password: Calyptus86
          
#      - name: Build the Docker image
#        run: docker build . --file dockerfile -t rmanohar86/kubelearning
      
#      - name: Push the Docker image
#        run : docker push rmanohar86/kubelearning
      - name: build image
        run: |
          docker-compose -f /containers/docker-compose.yml build
      
      - name: push image
        run : |
          docker-compose push
