name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: List files in the repository
        run: |
            ls 

      - name: Build the Docker image
        run: docker build . --file dockerfile --tag kubelearning:$(date +%s)
      
      - name: Push the Docker image
        run : docker push rmanohar86/kubelearning:$(date +%s)
